name: "Build Firmware"
on: [push]
# workflow_dispatch:
# push:
#   paths:
#     - "config/*"
#     - "build.yaml"
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

